# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EngineerHead
email: engineerhead@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog covers personal and professional expereinces of EngineerHead
twitter_username: engineerhead_head
github_username: engineerhead
minimal_mistakes_skin: dark
search: true
website: https://engineerhead.github.io
url: https://engineerhead.github.io

# Build settings
repository: engineerhead/engineerhead.github.io
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  # - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Engineer Head"
  avatar: "/assets/images/bio.jpeg"
  bio: "I try to make silicon understand when to switch on or off."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://engineerhead.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/engineered_head"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/engineerhead"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/engineered_head"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/engineerhead"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-JN7EGWW6WQ"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "engineerheads-blog"
